const EX={
"Respiration abdominale":{time:180,desc:"Respiration lente pour engager le diaphragme et faire redescendre le rythme.",steps:["Dos droit, épaules relâchées.","Pose une main sur le ventre.","Inspire par le nez pendant 4 secondes en laissant le ventre se gonfler.","Expire doucement pendant 6 secondes en laissant le ventre rentrer.","La poitrine bouge peu et tu ne bloques jamais la respiration."]},
"Posture du cavalier":{time:30,desc:"Travail de stabilité, d’ancrage et d’endurance des jambes.",steps:["Pieds un peu plus larges que les épaules.","Pointes légèrement ouvertes.","Fléchis comme pour t’asseoir, sans laisser les genoux rentrer.","Dos long, bassin neutre, respiration lente."]},
"Lever les mains":{desc:"Ouverture douce des épaules coordonnée à la respiration.",steps:["Pieds parallèles, genoux souples.","Inspire en levant lentement les mains devant toi.","Garde les épaules basses.","Expire en redescendant les bras."]},
"Séparer la crinière du cheval sauvage":{desc:"Coordination des bras et transfert de poids.",steps:["Imagine tenir une balle entre les mains.","Avance un pied et transfère doucement le poids.","Une main avance et monte, l’autre descend vers la hanche.","Reviens au centre et change de côté."]},
"Brosser le genou":{desc:"Équilibre et coordination croisée.",steps:["Avance un pied sans verrouiller le genou.","Une main passe devant le genou.","L’autre pousse à hauteur de poitrine.","Garde le buste droit puis change de côté."]},
"Déplacement lent":{desc:"Déplacer le centre de gravité avec contrôle.",steps:["Pose d’abord le talon.","Déroule le pied.","Transfère le poids progressivement.","Pour reculer, décharge d’abord le pied avant."]},
"Transfert de poids":{desc:"Base du tai-chi pour améliorer l’équilibre.",steps:["Pieds plus larges que le bassin.","Déplace le poids sur une jambe.","L’autre jambe devient légère.","Passe d’un côté à l’autre sans balancer le torse."]},
"Grue blanche déploie ses ailes":{desc:"Ouverture des épaules, équilibre et coordination.",steps:["Transfère le poids sur une jambe.","Monte un bras en arrondi, l’autre descend.","Épaules basses, coudes souples.","Redescends puis change de côté."]},
"Repousser le singe":{desc:"Stabilité du tronc et coordination en reculant.",steps:["Recule un pied avec contrôle.","Une main pousse devant, l’autre revient près de la hanche.","Tourne légèrement le torse sans forcer.","Alterne les côtés."]},
"Fermeture de la forme":{desc:"Retour au calme.",steps:["Ramène les pieds parallèles.","Mains devant le ventre.","Inspire en les montant légèrement.","Expire en les redescendant et relâche le corps."]}
};
const weeks={1:{label:"Apprentissage",days:{1:{title:"Poussée + Tai Chi",color:"blue",ex:[["Pompes","4 × 8"],["Pompes inclinées","2 × 10"],["Pike push-ups","3 × 6"],["Pompes diamant","2 × 6"],["Gainage","3 × 30 s",30],["Respiration abdominale","3 min",180],["Posture du cavalier","3 × 30 s",30],["Lever les mains","6 répétitions"],["Séparer la crinière du cheval sauvage","5 par côté"],["Brosser le genou","5 par côté"]]},3:{title:"Jambes + Core + Tai Chi",color:"green",ex:[["Squats","4 × 15"],["Fentes","3 × 10 par jambe"],["Squat isométrique au mur","3 × 30 s",30],["Pont fessier","3 × 15"],["Mollets","4 × 20"],["Dead bug","3 × 12"],["Hollow hold","3 × 20 s",20],["Déplacement lent","3 min"],["Transfert de poids","3 min"],["Respiration abdominale","4 min",240]]},5:{title:"Dos + Tai Chi",color:"purple",ex:[["Superman","4 × 12"],["Superman maintien","3 × 30 s",30],["Snow angels au sol","3 × 12"],["Y-T-W au sol","3 × 10"],["Bird dog","3 × 12 par jambe"],["Planche latérale","3 × 30 s par côté",30],["Grue blanche déploie ses ailes","5 par côté"],["Repousser le singe","5 par côté"],["Fermeture de la forme","3 min"],["Respiration abdominale","4 min",240]]}}},2:{label:"Progression",days:{}},3:{label:"Consolidation",days:{}}};
function cloneWeek(base,m){return Object.fromEntries(Object.entries(base).map(([d,v])=>[d,{...v,ex:v.ex.map(([n,r,t])=>[n,r.replace(/\d+/g,x=>String(Math.max(1,Math.round(+x*m)))),t?Math.round(t*m):t])}]))}
weeks[2].days=cloneWeek(weeks[1].days,1.2);weeks[3].days=cloneWeek(weeks[1].days,1.4);
const defaults={week:1,done:{},history:[],rest:60,dark:false,sound:true,vibration:true,records:{},notes:{},started:{}};
const state=Object.assign(defaults,JSON.parse(localStorage.getItem("fitState")||"{}"));
const $=s=>document.querySelector(s), slug=s=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
function save(){localStorage.setItem("fitState",JSON.stringify(state));document.documentElement.dataset.theme=state.dark?"dark":"light"}
function sessionKey(w,d){return `${w}-${d}`} function nearestDay(){let d=new Date().getDay();return d<=1?1:d<=3?3:5} function currentDay(){return +(localStorage.getItem("selectedDay")||nearestDay())}
function esc(s){return s.replaceAll("'","\\'")}
function renderToday(){let d=currentDay(),data=weeks[state.week].days[d],key=sessionKey(state.week,d),done=state.done[key]||[],pct=Math.round(done.length/data.ex.length*100),started=state.started[key];
$("#today").innerHTML=`<div class="card hero"><div><p class="eyebrow">SEMAINE ${state.week} · ${weeks[state.week].label.toUpperCase()}</p><h2>${data.title}</h2><p>${pct}% terminé · ${done.length}/${data.ex.length} exercices</p></div><div class="ring" style="--p:${pct}"><span>${pct}%</span></div></div>
<div class="week-selector">${[1,2,3].map(w=>`<button class="${w===state.week?"active":""}" onclick="selectWeek(${w})">Semaine ${w}</button>`).join("")}</div>
<div class="card"><div class="session-title"><div><h2>${["","Lundi","","Mercredi","","Vendredi"][d]}</h2><p class="small">${started?"Séance en cours":"Prêt pour commencer ?"}</p></div><span class="badge">${weeks[state.week].label}</span></div><div class="progress"><span style="width:${pct}%"></span></div>
${!started?`<button class="primary wide start" onclick="startSession()">▶ Commencer la séance</button>`:""}
<div class="exercise-list">${data.ex.map((e,i)=>exerciseRow(e,i,done.includes(i),started)).join("")}</div>
<div class="actions"><button class="primary" onclick="finishSession()">Terminer</button><button class="secondary" onclick="resetSession()">Réinitialiser</button></div></div>
<div class="card compact"><div class="section-label">CHOISIR LA SÉANCE</div><div class="actions day-switch"><button onclick="setDay(1)">Lun.</button><button onclick="setDay(3)">Mer.</button><button onclick="setDay(5)">Ven.</button></div></div>`}
function exerciseRow(e,i,done,started){let[n,r,t]=e;return `<div class="exercise ${done?"completed":""}"><button class="check ${done?"done":""}" onclick="toggleExercise(${i})">${done?"✓":""}</button><img class="thumb" src="exercises/${slug(n)}.png" alt="Illustration ${n}" onclick="showExercise('${esc(n)}')"><div class="exercise-main" onclick="showExercise('${esc(n)}')"><h3>${n}</h3><p>${r}</p>${state.records[n]?`<span class="record">Record : ${state.records[n]}</span>`:""}</div>${t?`<button class="icon-btn" onclick="openTimer('${esc(n)}',${t})">⏱</button>`:`<button class="icon-btn" onclick="showExercise('${esc(n)}')">?</button>`}</div>`}
window.startSession=()=>{state.started[sessionKey(state.week,currentDay())]=Date.now();save();renderToday()};
window.selectWeek=w=>{state.week=w;save();renderAll()};window.setDay=d=>{localStorage.setItem("selectedDay",d);renderToday()};
window.toggleExercise=i=>{let key=sessionKey(state.week,currentDay());state.done[key]??=[];let p=state.done[key].indexOf(i);if(p>=0)state.done[key].splice(p,1);else{state.done[key].push(i);if(state.started[key])startRest();}save();renderToday()};
window.resetSession=()=>{let k=sessionKey(state.week,currentDay());state.done[k]=[];delete state.started[k];save();renderToday()};
window.finishSession=()=>$("#finishDialog").showModal();
$("#rpe").oninput=e=>$("#rpeValue").textContent=e.target.value;
window.confirmFinish=()=>{let d=currentDay(),data=weeks[state.week].days[d],key=sessionKey(state.week,d),start=state.started[key]||Date.now()-30*60000;state.done[key]=data.ex.map((_,i)=>i);state.history.unshift({id:Date.now(),date:new Date().toISOString(),week:state.week,day:d,title:data.title,count:data.ex.length,duration:Math.max(1,Math.round((Date.now()-start)/60000)),rpe:+$("#rpe").value,notes:$("#sessionNotes").value});delete state.started[key];save();$("#finishDialog").close();renderAll();buzz([150,80,220])};
window.showExercise=n=>{let d=EX[n]||{desc:"Effectue le mouvement lentement, proprement et sans douleur.",steps:["Stabilise ta posture.","Contrôle l’aller et le retour.","Expire pendant l’effort.","Arrête en cas de douleur articulaire."]};let rec=state.records[n]||"";$("#exerciseDetails").innerHTML=`<img class="detail-art" src="exercises/${slug(n)}.png"><p class="eyebrow">FICHE EXERCICE</p><h2>${n}</h2><p>${d.desc}</p><ol class="details-steps">${d.steps.map(s=>`<li>${s}</li>`).join("")}</ol><label>Meilleure performance<input id="recordInput" value="${rec}" placeholder="Ex. 20 répétitions ou 60 s"></label><button class="primary wide" onclick="saveRecord('${esc(n)}')">Enregistrer le record</button>`;$("#exerciseDialog").showModal()};
window.saveRecord=n=>{state.records[n]=$("#recordInput").value.trim();save();$("#exerciseDialog").close();renderAll()};
let timerId,remaining=30,initial=30;window.openTimer=(n,s)=>{initial=remaining=s;$("#timerName").textContent=n;updateTimer();clearInterval(timerId);timerId=null;$("#timerStart").textContent="Démarrer";$("#timerDialog").showModal()};function updateTimer(){$("#timerDisplay").textContent=`${String(Math.floor(remaining/60)).padStart(2,"0")}:${String(remaining%60).padStart(2,"0")}`}
$("#timerStart").onclick=()=>{if(timerId){clearInterval(timerId);timerId=null;$("#timerStart").textContent="Reprendre";return}$("#timerStart").textContent="Pause";timerId=setInterval(()=>{remaining--;updateTimer();if(remaining<=0){clearInterval(timerId);timerId=null;$("#timerStart").textContent="Terminé";buzz([200,100,200]);beep()}},1000)};$("#timerReset").onclick=()=>{clearInterval(timerId);timerId=null;remaining=initial;updateTimer();$("#timerStart").textContent="Démarrer"};
let restId,restLeft=0;function startRest(){clearInterval(restId);restLeft=state.rest;$("#miniTimer").classList.remove("hidden");tickRest();restId=setInterval(()=>{restLeft--;tickRest();if(restLeft<=0){skipRest();buzz([120,70,120]);beep()}},1000)}function tickRest(){$("#miniTimerValue").textContent=`${String(Math.floor(restLeft/60)).padStart(2,"0")}:${String(restLeft%60).padStart(2,"0")}`}window.skipRest=()=>{clearInterval(restId);$("#miniTimer").classList.add("hidden")};
function buzz(p){if(state.vibration)navigator.vibrate?.(p)}function beep(){if(!state.sound)return;try{let c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=660;g.gain.value=.08;o.start();o.stop(c.currentTime+.18)}catch{}}
function renderProgram(){$("#program").innerHTML=`<div class="card"><h2>Programme sur 3 semaines</h2><p class="small">Progression automatique, sans matériel.</p></div>${[1,2,3].map(w=>`<div class="card"><h2>Semaine ${w} · ${weeks[w].label}</h2>${[1,3,5].map(d=>{let x=weeks[w].days[d];return `<button class="program-day ${x.color}" onclick="selectWeek(${w});setDay(${d});openView('today')"><strong>${["","Lundi","","Mercredi","","Vendredi"][d]} — ${x.title}</strong><span>${x.ex.length} exercices ›</span></button>`}).join("")}</div>`).join("")}<div class="card"><h2>Guide illustré complet</h2><img class="infographic" src="programme.png" alt="Programme illustré"></div>`}
function streak(){let days=[...new Set(state.history.map(h=>h.date.slice(0,10)))].sort().reverse(),s=0,d=new Date();for(let i=0;i<60;i++){let x=d.toISOString().slice(0,10);if(days.includes(x))s++;else if(i>0)break;d.setDate(d.getDate()-1)}return s}
function chart(){let vals=[...state.history].reverse().slice(-12);if(!vals.length)return '<div class="empty">Termine une séance pour voir ta progression.</div>';let max=10,w=320,h=110,pts=vals.map((v,i)=>`${20+i*(280/Math.max(1,vals.length-1))},${95-(v.rpe/max)*75}`).join(' ');return `<svg class="chart" viewBox="0 0 320 110"><line x1="20" y1="95" x2="300" y2="95"/><polyline points="${pts}"/><text x="20" y="108">Ancien</text><text x="270" y="108">Récent</text></svg>`}
function renderHistory(){let h=state.history,total=h.reduce((a,x)=>a+x.duration,0);$("#history").innerHTML=`<div class="stats"><div class="stat"><strong>${h.length}</strong><span>Séances</span></div><div class="stat"><strong>${streak()}</strong><span>Série</span></div><div class="stat"><strong>${total}</strong><span>Minutes</span></div></div><div class="card"><h2>Difficulté ressentie</h2>${chart()}</div><div class="card"><h2>Historique</h2>${h.length?h.map(x=>`<div class="history-item"><div><strong>${x.title}</strong><div class="small">${new Date(x.date).toLocaleDateString("fr-FR")} · ${x.duration} min · difficulté ${x.rpe}/10</div>${x.notes?`<div class="note">${x.notes}</div>`:""}</div><button class="delete" onclick="deleteHistory(${x.id})">×</button></div>`).join(""):'<div class="empty">Aucune séance enregistrée.</div>'}</div>`}
window.deleteHistory=id=>{state.history=state.history.filter(x=>x.id!==id);save();renderHistory()};
function renderSettings(){$("#settings").innerHTML=`<div class="card"><h2>Réglages</h2><div class="setting-row"><div><strong>Temps de repos</strong><div class="small">Lancé après un exercice validé</div></div><select onchange="state.rest=+this.value;save()">${[30,45,60,90,120].map(v=>`<option value="${v}" ${state.rest===v?'selected':''}>${v} s</option>`).join('')}</select></div><div class="setting-row"><div><strong>Mode sombre</strong></div><input type="checkbox" ${state.dark?'checked':''} onchange="state.dark=this.checked;save()"></div><div class="setting-row"><div><strong>Son de fin</strong></div><input type="checkbox" ${state.sound?'checked':''} onchange="state.sound=this.checked;save()"></div><div class="setting-row"><div><strong>Vibrations</strong></div><input type="checkbox" ${state.vibration?'checked':''} onchange="state.vibration=this.checked;save()"></div></div><div class="card"><h2>Sauvegarde</h2><p class="small">Exporte régulièrement tes données. Elles restent sinon uniquement sur cet iPhone.</p><div class="actions"><button class="secondary" onclick="exportData()">Exporter</button><label class="secondary file-label">Importer<input type="file" accept="application/json" onchange="importData(this.files[0])"></label></div></div><div class="card"><h2>Conseil adaptatif</h2><p>${recommendation()}</p></div><div class="actions"><button class="danger" onclick="clearData()">Effacer toutes les données</button></div>`}
function recommendation(){let h=state.history.slice(0,3);if(!h.length)return "Termine ta première séance pour obtenir une recommandation.";let avg=h.reduce((a,x)=>a+x.rpe,0)/h.length;if(avg>=8)return "Tes dernières séances sont difficiles : garde la même semaine ou réduis chaque série de 1 à 2 répétitions.";if(avg<=5)return "Tu sembles à l’aise : passe à la semaine suivante ou ajoute 1 à 2 répétitions par série.";return "Charge bien dosée : poursuis le programme prévu et privilégie une exécution propre."}
window.exportData=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`entrainement-${new Date().toISOString().slice(0,10)}.json`;a.click()};window.importData=f=>{if(!f)return;let r=new FileReader();r.onload=()=>{try{Object.assign(state,JSON.parse(r.result));save();renderAll();alert('Sauvegarde importée.')}catch{alert('Fichier invalide.')}};r.readAsText(f)};window.clearData=()=>{if(confirm("Effacer l’historique et les réglages ?")){localStorage.removeItem("fitState");location.reload()}};
function renderAll(){renderToday();renderProgram();renderHistory();renderSettings()}window.openView=id=>{document.querySelectorAll('.tabbar button,.view').forEach(x=>x.classList.remove('active'));document.querySelector(`[data-view="${id}"]`)?.classList.add('active');$('#'+id).classList.add('active')};document.querySelectorAll('.tabbar button').forEach(b=>b.onclick=()=>openView(b.dataset.view));document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
let deferredPrompt;addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{await deferredPrompt?.prompt();deferredPrompt=null};if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));save();renderAll();
