const EX = {
  "Respiration abdominale": {time:180, desc:"Respiration lente pour calmer le rythme et engager le diaphragme.", steps:["Debout ou assis, dos droit et épaules relâchées.","Pose une main sur le ventre.","Inspire par le nez pendant environ 4 secondes : le ventre se gonfle.","Expire doucement pendant environ 6 secondes : le ventre rentre.","Garde la poitrine aussi immobile que possible."]},
  "Posture du cavalier": {time:30, desc:"Travail des jambes, de la stabilité et de l’ancrage.",steps:["Écarte les pieds un peu plus que les épaules.","Oriente légèrement les pointes vers l’extérieur.","Fléchis les genoux comme pour t’asseoir.","Garde le dos droit, le bassin neutre et les genoux alignés avec les pieds.","Respire lentement sans bloquer."]},
  "Lever les mains": {desc:"Mouvement doux d’ouverture des épaules coordonné à la respiration.",steps:["Pieds parallèles et genoux souples.","Inspire en levant lentement les mains devant toi.","Arrête vers la hauteur des épaules ou de la tête, sans hausser les épaules.","Expire en redescendant les bras."]},
  "Séparer la crinière du cheval sauvage": {desc:"Transfert de poids et coordination des bras.",steps:["Avance un pied et transfère progressivement le poids vers l’avant.","Imagine tenir une balle entre tes mains.","Une main avance et monte pendant que l’autre descend près de la hanche.","Reviens au centre puis change de côté."]},
  "Brosser le genou": {desc:"Coordination, équilibre et déplacement contrôlé.",steps:["Avance un pied sans verrouiller le genou.","Une main passe doucement devant le genou comme pour le brosser.","L’autre main pousse vers l’avant à hauteur de poitrine.","Garde le buste droit puis change de côté."]},
  "Déplacement lent": {desc:"Apprend à déplacer le centre de gravité sans perdre l’équilibre.",steps:["Avance le talon en premier.","Pose progressivement le pied.","Transfère lentement le poids vers l’avant.","Pour reculer, décharge d’abord le pied avant."]},
  "Transfert de poids": {desc:"Base essentielle du tai-chi.",steps:["Pieds plus larges que le bassin.","Déplace lentement le poids sur une jambe.","L’autre jambe reste légère mais en contact avec le sol.","Passe d’un côté à l’autre sans balancer le buste."]},
  "Grue blanche déploie ses ailes": {desc:"Ouverture, équilibre et relâchement des épaules.",steps:["Transfère le poids sur une jambe.","Monte un bras en arrondi pendant que l’autre descend.","Garde les épaules basses et les coudes souples.","Redescends lentement puis change de côté."]},
  "Repousser le singe": {desc:"Coordination arrière et stabilité du tronc.",steps:["Recule un pied avec contrôle.","Une main pousse devant toi tandis que l’autre revient près de la hanche.","Tourne légèrement le torse sans forcer le bas du dos.","Alterne lentement les côtés."]},
  "Fermeture de la forme": {desc:"Retour au calme en fin de pratique.",steps:["Ramène les pieds parallèles.","Place les mains devant le ventre.","Inspire en les montant légèrement.","Expire en les redescendant et relâche tout le corps."]}
};

const weeks = {
1:{label:"Apprentissage",days:{
  1:{title:"Poussée + Tai Chi",color:"blue",ex:[['Pompes','4 × 8'],['Pompes inclinées','2 × 10'],['Pike push-ups','3 × 6'],['Pompes diamant','2 × 6'],['Gainage','3 × 30 s',30],['Respiration abdominale','3 min',180],['Posture du cavalier','3 × 30 s',30],['Lever les mains','6 répétitions'],['Séparer la crinière du cheval sauvage','5 par côté'],['Brosser le genou','5 par côté']]},
  3:{title:"Jambes + Core + Tai Chi",color:"green",ex:[['Squats','4 × 15'],['Fentes','3 × 10 par jambe'],['Squat isométrique au mur','3 × 30 s',30],['Pont fessier','3 × 15'],['Mollets','4 × 20'],['Dead bug','3 × 12'],['Hollow hold','3 × 20 s',20],['Déplacement lent','3 min'],['Transfert de poids','3 min'],['Respiration abdominale','4 min',240]]},
  5:{title:"Dos + Tai Chi",color:"purple",ex:[['Superman','4 × 12'],['Superman maintien','3 × 30 s',30],['Snow angels au sol','3 × 12'],['Y-T-W au sol','3 × 10'],['Bird dog','3 × 12 par jambe'],['Planche latérale','3 × 30 s par côté',30],['Grue blanche déploie ses ailes','5 par côté'],['Repousser le singe','5 par côté'],['Fermeture de la forme','3 min'],['Respiration abdominale','4 min',240]]}
}},
2:{label:"Progression",days:{}},3:{label:"Consolidation",days:{}}
};
function cloneWeek(base, mult){return Object.fromEntries(Object.entries(base).map(([d,v])=>[d,{...v,ex:v.ex.map(([n,r,t])=>[n,progressText(r,mult),t?Math.round(t*mult):t])}]))}
function progressText(t,m){return t.replace(/(\d+)/g,(x)=>String(Math.max(1,Math.round(Number(x)*m))))}
weeks[2].days=cloneWeek(weeks[1].days,1.2); weeks[3].days=cloneWeek(weeks[1].days,1.4);
const state=JSON.parse(localStorage.getItem('fitState')||'{"week":1,"done":{},"history":[],"rest":60}');
function save(){localStorage.setItem('fitState',JSON.stringify(state))}
function sessionKey(w,d){return `${w}-${d}`}
function nearestDay(){const day=new Date().getDay(); return day<=1?1:day<=3?3:5}
function currentDay(){return Number(localStorage.getItem('selectedDay')||nearestDay())}
function setDay(d){localStorage.setItem('selectedDay',d);renderToday()}
function renderToday(){const d=currentDay(), data=weeks[state.week].days[d], key=sessionKey(state.week,d), completed=state.done[key]||[]; const total=data.ex.length, pct=Math.round(completed.length/total*100);
 document.querySelector('#today').innerHTML=`
 <div class="card hero"><p class="eyebrow">SEMAINE ${state.week} · ${weeks[state.week].label.toUpperCase()}</p><h2>${data.title}</h2><p>${pct}% terminé · ${completed.length}/${total} exercices</p></div>
 <div class="week-selector">${[1,2,3].map(w=>`<button class="${w===state.week?'active':''}" onclick="selectWeek(${w})">Semaine ${w}</button>`).join('')}</div>
 <div class="card"><div class="session-title"><div><h2>${['','Lundi','', 'Mercredi','', 'Vendredi'][d]}</h2><p class="small">Touchez un exercice pour voir les consignes.</p></div><span class="badge">${weeks[state.week].label}</span></div><div class="progress"><span style="width:${pct}%"></span></div>
 ${data.ex.map((e,i)=>exerciseRow(e,i,completed.includes(i))).join('')}
 <div class="actions"><button class="primary" onclick="finishSession()">Terminer la séance</button><button class="secondary" onclick="resetSession()">Réinitialiser</button></div></div>
 <div class="card"><div class="section-label">CHOISIR LA SÉANCE</div><div class="actions"><button class="secondary" onclick="setDay(1)">Lundi</button><button class="secondary" onclick="setDay(3)">Mercredi</button><button class="secondary" onclick="setDay(5)">Vendredi</button></div></div>`}
function exerciseRow(e,i,done){const [n,r,t]=e; return `<div class="exercise"><button class="check ${done?'done':''}" onclick="toggleExercise(${i})">${done?'✓':''}</button><div onclick="showExercise('${escapeQ(n)}')"><h3>${n}</h3><p>${r}</p></div>${t?`<button class="icon-btn" onclick="openTimer('${escapeQ(n)}',${t})">⏱</button>`:`<button class="icon-btn" onclick="showExercise('${escapeQ(n)}')">?</button>`}</div>`}
function escapeQ(s){return s.replaceAll("'","\\'")}
window.selectWeek=w=>{state.week=w;save();renderAll()};
window.toggleExercise=i=>{const key=sessionKey(state.week,currentDay());state.done[key]=state.done[key]||[];const p=state.done[key].indexOf(i);p>=0?state.done[key].splice(p,1):state.done[key].push(i);save();renderToday()};
window.resetSession=()=>{state.done[sessionKey(state.week,currentDay())]=[];save();renderToday()};
window.finishSession=()=>{const d=currentDay(), data=weeks[state.week].days[d], key=sessionKey(state.week,d);state.done[key]=data.ex.map((_,i)=>i);state.history.unshift({date:new Date().toISOString(),week:state.week,title:data.title,count:data.ex.length});save();renderAll();navigator.vibrate?.(120)};
window.setDay=setDay;
window.showExercise=n=>{const d=EX[n]||{desc:"Effectue le mouvement lentement et proprement, sans douleur.",steps:["Garde une posture stable.","Contrôle la descente et la remontée.","Respire régulièrement.","Arrête en cas de douleur articulaire."]};document.querySelector('#exerciseDetails').innerHTML=`<p class="eyebrow">EXPLICATION</p><h2>${n}</h2><p>${d.desc}</p><ol class="details-steps">${d.steps.map(s=>`<li>${s}</li>`).join('')}</ol>`;document.querySelector('#exerciseDialog').showModal()};
let timerId=null, remaining=30, initial=30; window.openTimer=(n,s)=>{initial=remaining=s;document.querySelector('#timerName').textContent=n;updateTimer();document.querySelector('#timerStart').textContent='Démarrer';clearInterval(timerId);timerId=null;document.querySelector('#timerDialog').showModal()};
function updateTimer(){document.querySelector('#timerDisplay').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`}
document.querySelector('#timerStart').onclick=()=>{if(timerId){clearInterval(timerId);timerId=null;document.querySelector('#timerStart').textContent='Reprendre';return}document.querySelector('#timerStart').textContent='Pause';timerId=setInterval(()=>{remaining--;updateTimer();if(remaining<=0){clearInterval(timerId);timerId=null;navigator.vibrate?.([200,100,200]);document.querySelector('#timerStart').textContent='Terminé'}},1000)};
document.querySelector('#timerReset').onclick=()=>{clearInterval(timerId);timerId=null;remaining=initial;updateTimer();document.querySelector('#timerStart').textContent='Démarrer'};
document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
function renderProgram(){document.querySelector('#program').innerHTML=`<div class="card"><h2>Programme sur 3 semaines</h2><p class="small">Trois séances par semaine, sans barre ni élastique.</p></div>${[1,2,3].map(w=>`<div class="card"><h2>Semaine ${w} · ${weeks[w].label}</h2>${[1,3,5].map(d=>{const x=weeks[w].days[d];return `<div class="day-card ${x.color}"><h3>${['','Lundi','','Mercredi','','Vendredi'][d]} — ${x.title}</h3><p>${x.ex.map(e=>e[0]).join(' · ')}</p></div>`}).join('')}</div>`).join('')}<div class="card"><h2>Infographie complète</h2><img class="infographic" src="programme.png" alt="Programme illustré callisthénie et tai chi" /></div>`}
function renderHistory(){const h=state.history;document.querySelector('#history').innerHTML=`<div class="card"><h2>Historique</h2>${h.length?h.map(x=>`<div class="history-item"><div><strong>${x.title}</strong><div class="small">Semaine ${x.week} · ${new Date(x.date).toLocaleDateString('fr-FR')}</div></div><span class="badge">${x.count} exercices</span></div>`).join(''):'<div class="empty">Aucune séance terminée pour le moment.</div>'}</div><div class="card"><div class="streak">${h.length}</div><div class="small">séance${h.length>1?'s':''} enregistrée${h.length>1?'s':''}</div></div>`}
function renderSettings(){document.querySelector('#settings').innerHTML=`<div class="card"><h2>Réglages</h2><div class="setting-row"><div><strong>Temps de repos</strong><div class="small">Entre deux séries</div></div><select onchange="state.rest=Number(this.value);save()"><option value="45" ${state.rest===45?'selected':''}>45 s</option><option value="60" ${state.rest===60?'selected':''}>60 s</option><option value="90" ${state.rest===90?'selected':''}>90 s</option></select></div><div class="setting-row"><div><strong>Sauvegarde</strong><div class="small">Les données restent sur cet iPhone.</div></div></div><div class="actions"><button class="danger" onclick="clearData()">Effacer toutes les données</button></div></div><div class="notice">Ajout à l’écran d’accueil : ouvrez cette page dans Safari, touchez le bouton Partager, puis « Sur l’écran d’accueil ».</div>`}
window.clearData=()=>{if(confirm('Effacer tout l’historique et toutes les validations ?')){localStorage.removeItem('fitState');location.reload()}};
function renderAll(){renderToday();renderProgram();renderHistory();renderSettings()}
document.querySelectorAll('.tabbar button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabbar button,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.view).classList.add('active')});
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.querySelector('#installBtn').classList.remove('hidden')});document.querySelector('#installBtn').onclick=async()=>{await deferredPrompt?.prompt();deferredPrompt=null};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
renderAll();
